FreePBX/framework

- amp_conf/bin/freepbx-cron-scheduler.php
- amp_conf/bin/retrieve_conf
- amp_conf/htdocs/admin/libraries/BMO/GPG.class.php
- amp_conf/htdocs/admin/libraries/BMO/PKCS.class.php
- amp_conf/htdocs/admin/libraries/modulefunctions.class.php
There's a real bug on FreeBSD, where the environment that is
created before gpg and openssl are run have an invalid shell.
This one is important to fix.
The other change is a code refactoring of how the notifications
for unsigned/tampered modules are generated.  The git commit
message explains it.
> More fixups for FreeBSD and code refactoring

- install.php
The asterisk_conf array is not filled out, so the $agibin_dest was always being
set to /var/lib/asterisk/agi-bin when the installation script ran.
Use the value stored in the amp_conf database to figure out where to copy the
agi-bin scripts.
> Locate installed ASTAGIDIR correctly

- amp_conf/bin/retrieve_conf
If SIGNATURE_CHECK is disabled, retrieve_conf still tries to refresh them. IMO SIGNATURE_CHECK = false should totally disable signature validation operations
> Fix bug: SIGNATURE_CHECK setting ignored

- amp_conf/htdocs/admin/libraries/utility.functions.php
The addition of the getSystemMemInfo function into the 'framework' module causes
it to fail to run on FreeBSD systems.  This is a minimal patch to supply the
one data value that is used by the caller.
> Make getSystemMemInfo work on FreeBSD

- amp_conf/htdocs/admin/helpers/Table.php
- amp_conf/htdocs/admin/views/footer.php
- amp_conf/htdocs/admin/views/menu.php
During html5 validation checks, came across some issues.  In addition to missing ? on echo, match div's from views/header.php to views/footer.php.  Header leaves one open div "page" but footer was attempting to close two divs at page_body prior to adding actual footer content.
> framework cleanups for valid html5 generation

- amp_conf/htdocs/admin/libraries/Console/Chown.class.php
> treat custom permissions as integer, not string

- amp_conf/htdocs/admin/libraries/Console/Chown.class.php
- amp_conf/htdocs/admin/views/footer.php
Fixes FREEPBX-13253.
Also addresses unrelated "undefined index" notice.
> Correctly process "rdir" and "execdir" sections of freepbx_chown.conf

- amp_conf/htdocs/admin/libraries/BMO/Database/Migration.class.php
this works well for me in testing. `$data['foreigncols']` and `$data['cols']` are both arrays; `$data['options']` looks something like this:
$options = ["onupdate"=>"CASCADE", "ondelete"=>"CASCADE"];
> allow foreign keys

- amp_conf/htdocs/admin/libraries/modulefunctions.class.php
Running `fwconsole ma downloadinstall http://example.com/foo.tgz?version=123` doesn't work because it's looking at `.tgz?version=123` as the filename suffix. This patch parses the URL properly, removing the query string.
> don't break on URL query strings

- amp_conf/htdocs/admin/libraries/modulefunctions.class.php
- amp_conf/htdocs/admin/page.modules.php
Re [FREEPBX-14064](http://issues.freepbx.org/browse/FREEPBX-14064)
This was easier than I expected, but it seems to work. Tested updates successfully, and confirmed that version dependencies are handled the same way as standard modules.
Within `module.xml`, an `<updateurl>` element contains a link to a JSON file that looks like this:
```json
{
"rawname": "module",
"repo": "local",
"name": "Module",
"version": "2.3",
"publisher": "Publisher",
"license": "GPLv3+",
"licenselink": "http://www.gnu.org/licenses/gpl-3.0.txt",
"changelog": "Some changes",
"category": "Admin",
"description": "A module",
"depends": {
"version": "13.0",
"phpversion": "5.6"
},
"supported": {
"version": "13.0"
},
"location": "https://download.example.com/modules/module-2.3.tgz",
"md5sum": …
```
> Allow third party modules to specify a remote update URL

- amp_conf/htdocs/admin/libraries/BMO/GPG.class.php
Add missing backslash before Exception handler when
no valid gpg binary is found.
> Add /usr/local/bin/gpg2 as a valid gpg binary

- amp_conf/htdocs/admin/libraries/BMO/DialplanHooks.class.php
- amp_conf/htdocs/admin/libraries/BMO/FileHooks.class.php
- amp_conf/htdocs/admin/libraries/BMO/GuiHooks.class.php
- amp_conf/htdocs/admin/libraries/BMO/Hooks.class.php
- amp_conf/htdocs/admin/libraries/BMO/Self_Helper.class.php
PHP namespaces are case-insensitive, this patch ensures that framework code treats them as such. In the event you declare `namespace FreePBX\Modules` or `namespace FreePbx\modules` your module will not function properly. (This manifested for my module as `myGuiHooks()` and `myConfigPageInits()` not being seen.)
> Ensure namespacing is case-insensitive

- amp_conf/htdocs/admin/assets/less/freepbx/page.less
Increases spacing at bottom of table, and also displays a pointer over the table rows (I couldn't think of any modules where they aren't clickable.)
Before:
After:
> cosmetic fixes for rightnav

- amp_conf/htdocs/admin/libraries/BMO/Cron.class.php
By default in fcrontab shows the first line the INFO, example:
2017-06-29 13:44:41  INFO listing root's fcrontab
If you don't send 2> to null , It's include in next update and it has thousands of INFO lines
------------------------------
2017-06-28 03:10:00  INFO listing asterisk's fcrontab
2017-06-28 03:10:00  INFO listing asterisk's fcrontab
2017-06-28 03:09:00  INFO listing asterisk's fcrontab
2017-06-28 03:09:00  INFO listing asterisk's fcrontab
2017-06-28 03:08:00  INFO listing asterisk's fcrontab
2017-06-28 03:08:00  INFO listing asterisk's fcrontab
2017-06-28 03:07:00  INFO listing asterisk's fcrontab
2017-06-28 03:07:00  INFO listing asterisk's fcrontab
2017-06-28 03:06:00  INFO listing asterisk's fcrontab
2017-06-28 03:06:00  INFO listing asterisk's fcrontab
2017-06-28 03:05:01 …
> Fix for fcrontab

- amp_conf/bin/retrieve_conf
In case `$bootstrap_settings["freepbx_error_handler"] = false;` is set in `/etc/freepbx.conf` then `$whoops` will be unset and trigger a fatal error when trying to use it.
> check that FreePBX error handler exists

- amp_conf/htdocs/admin/libraries/Console/Chown.class.php
Obviously if it's been specified on a single file, it's been done for a reason! Fixes FREEPBX-14185
> Don't strip executable on individual files

- amp_conf/htdocs/admin/libraries/BMO/ConfigFile.class.php
A single value in a section is a string instead of an array; this doesn't mean its value shouldn't get checked for a match before removing it.
Also added some braces around single-line blocks to match the rest of the code.
Resolves FREEPBX-16425
> Check the config file value before removing it

- amp_conf/htdocs/admin/assets/less/freepbx/page.less
This ensures the input's borders are not blurred, just the text.
I will be pushing out another PR on core that would resolve [FREEPBX-15896](https://issues.freepbx.org/browse/FREEPBX-15896) as discussed.
> blur the text only, not the entire element

- amp_conf/htdocs/admin/libraries/Console/Moduleadmin.class.php
Seems like the use of the "force" option is quite messed up here. Lots of functions in this class take a `$force` argument but then ignore it in favour of the class property `$this->force`
> Resolve undefined variable warning

- amp_conf/htdocs/admin/libraries/usage_registry.functions.php
`empty()` will also check for false but won't trigger a notice. Needs to be backported to 13.0 as well.
> Resolve undefined index notice

- amp_conf/htdocs/admin/libraries/BMO/Framework.class.php
Fix "PHP Fatal error:  Uncaught Error: Call to a member function connected() on null in /usr/local/src/freepbx/amp_conf/htdocs/admin/libraries/BMO/Framework.class.php:180" when no astman instance
https://issues.freepbx.org/browse/FREEPBX-19915
> check for astman instance before using it
